image: "golang:latest"

stages:
  - build
  - test
  - deploy

before_script:
  - cd $GOPATH/src
  - echo "In `pwd`"
  
  - ln -s $CI_PROJECT_DIR/code cloud
  - echo "Created symlink"
  - ls
  
  - cd $CI_PROJECT_DIR/code
  - echo "In `pwd`"

build:
  stage: build
  script:
    - make

test:
  stage: test
  script:
    - make test

deploy:
  stage: deploy
  script:
    - make deploy
